apiVersion: v1
kind: Pod
metadata: 
  name: go-app-pod 
  labels: 
    app: go 
    lab: lab2
spec:
  imagePullSecrets:
    - name: ghcr-secret
  containers:
  - name: go-app 
    image: ghcr.io/hyperslava/containers-lab-1/app:sha-0a34ffc 
    ports:
    - containerPort: 80 
    resources: 
      requests: 
        memory: "256Mi" 
        cpu: "250m" 
      limits: 
        memory: "512Mi" 
        cpu: "500m"